server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/sparkle-20221102?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
    tomcat:
      max-active: 5
      max-wait: 10000

mybatis:
  mapper-locations:
    - /mappers/*.xml

#파일 패스 각자 경로 설정해야 프로젝트폴더 -> upload폴더

#file:
# path: /Users/yulini/Desktop/spakle/upload/


file:
  path: C:/junil/changseok/web-basic/git/project/spakle/upload/
