server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/sparkle-20221102?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

thymeleaf:
  check-template-location: true
  suffix: .html
  mode: HTML5
  characterEncoding: utf-8
  cache: false
  order: 0
  prefix: classpath:/templates/

#파일 패스 각자 경로 설정해야 프로젝트폴더 -> upload폴더
file:
  path: C:/mungi/web/springboot/spakleCloneProject/upload/
